### PR TITLE
Monochrome OLED support using i2c

### PR DESCRIPTION
**Pull request by mathertel**
## Arduino Wire bus implementation

The Arduino Wire bus enables connecting displays using the i2c bus.
This is especially useful for smaller and monochrome displays.

To initialize the i2c bus the standard Wire configuration for the board can be used
by only specifying the i2c address:

```cpp
Arduino_DataBus *bus = new Arduino_Wire(i2cAddress);
```

When another special Wire interface should be used the Wire can be passed as a second parameter.

```cpp
  TwoWire *wire2 = new TwoWire();
  wire2->begin(SDA2, SCL2);
  bus = new Arduino_Wire(conf->i2cAddress, wire2);
```

### CODE REVIEW

**Comment by mathertel** [comment]
## Byte orientation in Canvas Mono

By using the last optional initialization parameter the Canvas Mono class can be configured to use horizontal 8 pixels or vertical 8 pixels in a byte.

This allows using the canvas storage in the same way the display driver needs the data.

```cpp
  Arduino_GFX *gfx = new Arduino_Canvas_Mono(conf->width, conf->height, op, 0, 0, true);
```

**Comment by mathertel** [comment]
## Arduino_SH1106 display implementation

To enable using the monochrome SH1106 OLED displays the Arduino_SH1106 enables sending the display buffer to the device.
The Arduino_Canvas_Mono is provided the display buffer and is used for drawing.
The whole buffer is sent as a bitmap for updates.

```cpp
  // Mono color Canvas
  Arduino_DataBus *bus = new Arduino_Wire(0x3C);
  Arduino_G *outputDriver = new Arduino_SH1106(bus, 128 /* width */, 64 /* height */);
  Arduino_GFX *gfx = new Arduino_Canvas_Mono(128 /* width */, 64 /* height */, outputDriver, 0 /* output_x */, 0 /* output_y */);
```

**Comment by moononournation** [comment]
Thanks for your contribution. Just a little bit about naming standard, I am still considering the data bus is it should call Arduino_HWI2C...

**Comment by mathertel** [comment]
> Just a little bit about naming standard, I am still considering the data bus is it should call Arduino_HWI2C...

Wire is an interface. It is sometimes Software based (ESP8266) and sometimes Hardware based (ESP32).

**Pull request merged**
