### PR TITLE
Add 3.71" and 4.58" displays plus column offset support

### PR DESCRIPTION
**Pull request by makermelissa**
This adds support for the 3.71" and 4.58" displays. Both use a buffer that is wider than the display area, so there is a new parameter called `overscan_left` which widens the buffer and shifts everything that is draw to it over by that amount. The row_stride is used due to a an IDF requirement that buffers be 16-bit aligned.

cc @ladyada

### CODE REVIEW

**Comment by moononournation** [comment]
The parameter name is a little bit odd. ST7735 and ST7789 also have similar sub area display, I think it should align with existing practice.

**Comment by makermelissa** [comment]
I'm fine with changing the name. I'll change it to `col_offset` as used in the displays you mentioned, which is pretty much what it is.

**Comment by moononournation** [comment]
More things to be aligned:
In ST7789, if the display is 170 width, then 2 col offsets are 35 and 35. But the ST7789_TFTWIDTH will keep as 240. so I think `_rgbpanel->row_stride` should be `_rgbpanel->width`.
And for future possible enhancement, the RGB display class should add all `uint8_t col_offset1 = 0, uint8_t row_offset1 = 0, uint8_t col_offset2 = 0, uint8_t row_offset2 = 0` parameters in the declaration.
Then `_rgbpanel->first_pixel_offset` is not required.

**Comment by makermelissa** [comment]
The reason for the row_stride is to get around one of the idiosyncrasies of the ESP IDF which fails if the col_offset + row_stride are not divisible by 16.

Getting back to what you were requesting, I can definitely add the additional offset parameters and then have the user manually handle making it divisible by 16 instead of automatically handling it for them.

Or if you'd prefer, I can have it adjust the requested values so that it doesn't cause the ESP IDF to fail.

**Comment by moononournation** [comment]
Auto adjust 16 alignment should be a good idea, but it may introduce some hard to debug situation. I prefer do not give too much nursery for the coder.

**Comment by makermelissa** [comment]
Ok, the requested changes have been made and tested.

**Comment by moononournation** [comment]
I have relocated the offset parameters to Arduino_RGB_Display class, so it is aligned to other display class.
Please help to get update and check is it ok.

**Pull request merged**
