### PR TITLE
Update Arduino_NV3023.cpp ( fix Rotation )

### PR DESCRIPTION
**Pull request by MakerM0**
fix Rotation

### CODE REVIEW

**Comment by moononournation** [comment]
Something need to confirm: Is the rotation orientation align with #46 ?

**Comment by MakerM0** [comment]
My display FPC is at the 6 o'clock position, so it is OK.

**Comment by MakerM0** [comment]
> 需要确认的事情：旋转方向是否与 #46 一致？

**Comment by moononournation** [comment]
The rotation should be:
1: clockwise 90 degree
2: 180 degree
3: clockwise 270 degree

**Comment by MakerM0** [comment]
> The rotation should be: 1: clockwise 90 degree 2: 180 degree 3: clockwise 270 degree


I have adjusted the code in a clockwise direction, and it's working fine now.

**Comment by moononournation** [comment]
ok, merge tonight

**Pull request merged**
