### PR TITLE
Add support for RTL8722DM_MINI and RTL8720DN_BW16

### PR DESCRIPTION
**Pull request by xidameng**

### CODE REVIEW

**Comment by xidameng** [comment]
Sorry for the extra commits, please review and squash merge the PR

**Comment by moononournation** [comment]
Now 3 boards defined 3 set of pins, is it possible 3 similar boards share same pins?

**Comment by moononournation** [comment]
For backward compatible, this line:
```
 #elif defined(BOARD_RTL8722DM)
```
should be something like that:
```
#elif defined(RTL8722DM) || defined(BOARD_RTL8722DM)
```

**Comment by xidameng** [comment]
> Now 3 boards defined 3 set of pins, is it possible 3 similar boards share same pins?

Hi, just checked again, but unfortunately, we can't, because 3 boards all use different set of SPI peripheral. and their numeric pin names are given differently too.

**Comment by xidameng** [comment]
> For backward compatible, this line:
> 
> ```
>  #elif defined(BOARD_RTL8722DM)
> ```
> 
> should be something like that:
> 
> ```
> #elif defined(RTL8722DM) || defined(BOARD_RTL8722DM)
> ```

sure, this can be done

**Comment by xidameng** [comment]
@moononournation I have done the changes, please take a look~

Note that macro `RTL8722DM` has been defined in all 3 dev boards, thus to differentiate, we must add an `AND` condition with the `BOARD_RTL872XXXX` macro

**Comment by moononournation** [comment]
Ok, RTL8722DM still exists in new version. Then for backward compatible, it should be something like that:
```
#elif defined(RTL8722DM)
#if defined(BOARD_RTL8722DM_MINI)
#define TFT_CS 12
#define TFT_DC 14
#define TFT_RST 15
#define TFT_BL 13
#elif defined(BOARD_RTL8720DN_BW16)
#define TFT_CS 9
#define TFT_DC 6
#define TFT_RST 2
#define TFT_BL 3
#else // defined(BOARD_RTL8722DM)
#define TFT_CS 18
#define TFT_DC 17
#define TFT_RST 2
#define TFT_BL 23
#endif
#elif ... other board ...
```

**Comment by xidameng** [comment]
> Ok, RTL8722DM still exists in new version. Then for backward compatible, it should be something like that:
> 
> ```
> #elif defined(RTL8722DM)
> #if defined(BOARD_RTL8722DM_MINI)
> #define TFT_CS 12
> #define TFT_DC 14
> #define TFT_RST 15
> #define TFT_BL 13
> #elif defined(BOARD_RTL8720DN_BW16)
> #define TFT_CS 9
> #define TFT_DC 6
> #define TFT_RST 2
> #define TFT_BL 3
> #else // defined(BOARD_RTL8722DM)
> #define TFT_CS 18
> #define TFT_DC 17
> #define TFT_RST 2
> #define TFT_BL 23
> #endif
> #elif ... other board ...
> ```

@moononournation 
Done

BTW, is BL necessary to define? can't we just use vcc for it so we can save a pin

**Pull request merged**
