### PR TITLE
Wire Bus and Mono-Color OLED improvements

### PR DESCRIPTION
**Pull request by mathertel**
This pull request is further enriching the functionality around using the Wire / I2C / TWI bus for displays and
closing functionality gaps in the Mono-Color OLED displays using the Canvas Mono for drawing.

Enhancing WireBus functionality
Enhancing Arduino_Canvas_Mono functionality
SH1106 support
SSD1306 support

See also #404 and #399

### CODE REVIEW

**Comment by moononournation** [comment]
I have reviewed the code and found AVR MCU may more wants mono display support. So I expose the writeBytes() to all MCU.
Then 3 things you need to revise:
1. Get update latest code
2. move all TWI related code to Arduino_Wire class
3. resubmit the request that do not need to touch Arduino_DataBus class

**Comment by mathertel** [comment]
I tried !
The topic is the extra prefix byte that needs to be transmitted for Commands and Data.
Either the display driver "knows" somehow that the bus is of type TWI and then provides the extra byte as data
or the bus driver takes over transmitting this extra byte.

**Comment by mathertel** [comment]
about `virtual void writeBytes(uint8_t *data, uint32_t len) = 0;`
This requires all sub-classes to implement the function and results in multiple implementations.
`virtual void writeBytes(uint8_t *data, uint32_t len) {}` avoids this.

**Comment by mathertel** [comment]
I like to talk about these design decisions as I do with the colleges in my professional environment before implementing several times in different software designs.
I hope you get my arguments and of course you should have the final design decision towards fulfilling great TWI and OLED support.

**Comment by moononournation** [comment]
Please resubmit a pull request, if you can make a Arduino_DataBus class change free version. You may refer to the existing various SPI classes for reference.

**Comment by mathertel** [comment]
> Please resubmit a pull request, if you can make a Arduino_DataBus class change free version. You may refer to the existing various SPI classes for reference.

This is a problem and cannot be done without exposing chip specifics to the bus initialisation/creation.
I can try again using this approach so you can see...

**Pull request closed without merging**
