### PR TITLE
Alternate ILI9341 init sequence

### PR DESCRIPTION
**Pull request by RealNobser**
- Fixed orientation / color issues with some ILI9341 drivers. Credits go to https://github.com/Bodmer/TFT_eSPI/issues/1172
- Fixed wrong byte count in ILI9341 standard init sequence

### CODE REVIEW

**Comment by moononournation** [comment]
fixed typo 3 to 5 first, the alternative init code should not require a separate class. Should redesign soon...

**Comment by moononournation** [comment]
The typo problem is caused by #322 so it will test the typo first.

**Comment by moononournation** [comment]
I have not yet determine use what method for same display model with different init code option. But I have tested 3 init code version, you proposed version have much better result in my display, especially on ImgViewerJpeg.ino photo. So I will adopt this init code first.

**Comment by RealNobser** [comment]
> I have not yet determine use what method for same display model with different init code option. But I have tested 3 init code version, you proposed version have much better result in my display, especially on ImgViewerJpeg.ino photo. So I will adopt this init code first.

Mine has an additional issue: It has to be inverted. That was one of the reasons why I implemented a separate class. Of course I can swap in the main application, but I tried to copy your way in the init method.

**Pull request closed without merging**
