### PR TITLE
Wire Bus and Mono-Color OLED improvements

### PR DESCRIPTION
**Pull request by mathertel**
This pull request is further enriching the  functionality around using the Wire / I2C / TWI bus for displays and
closing functionality gaps in the Mono-Color OLED displays using the Canvas Mono for drawing.

* Enhancing WireBus functionality
* Enhancing Arduino_Canvas_Mono functionality
* SH1106 support
* SSD1306 support

### CODE REVIEW

**Comment by moononournation** [comment]
Rejected, you actually require a writeBytes function. Don't abuse writePixels function to send 8 bit data.

**Comment by mathertel** [comment]
I like to send bytes of pixels to the databus.
In SPI the databus controls the 9th bit or dc Signal using the writePixel function.
In I2C there is a extra

**Comment by moononournation** [comment]
I your case, you should use write bytes.

**Comment by mathertel** [comment]
The I2C bus requires writing the correct prefix bytes before commands or pure data/pixels.
Also the max length of a I2c transfer must be known to the implementation and the prefix must be repeated on further data transfers.

I can rename to writeBytes but I thing writePixels is the better semantic name.

**Comment by moononournation** [comment]
databus already have write bytes function

**Pull request closed without merging**
